export default {
  editorMode: "web",
  content: [
    {
      id: "f8043f3e-9e88-46f8-92c0-00aeceddc2ab",
      type: "Row",
      attrs: {
        width: "100%",
        height: "auto",
        borderSize: 0,
        borderColor: "#000000",
        backgroundColor: "#e4e4e4",
        backgroundImage: "",
        backgroundSize: "",
        upload: "",
        direction: "vertical",
        alignment: "center",
        paddingTop: "4",
        paddingRight: 4,
        paddingBottom: "4",
        paddingLeft: 4,
        allowChildren: true,
        disableDelete: true,
      },
      content: [
        {
          id: "cbf27be5-9975-492f-9e9d-07b7e9d9d757",
          type: "Row",
          attrs: {
            width: "600px",
            height: "inherit",
            borderSize: "1",
            borderColor: "#a9aaab",
            backgroundColor: "#ffffff",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "center",
            paddingTop: "8",
            paddingRight: "8",
            paddingBottom: "8",
            paddingLeft: "8",
            allowChildren: true,
          },
          content: [
            {
              id: "8b9d9fad-0ac4-455c-8433-7f0788dc920b",
              type: "Row",
              attrs: {
                width: "100%",
                height: "inherit",
                borderSize: 0,
                borderColor: "#000000",
                backgroundColor: "transparent",
                backgroundImage: "",
                backgroundSize: "",
                upload: "",
                direction: "vertical",
                alignment: "center",
                paddingTop: "12",
                paddingRight: "0",
                paddingBottom: "12",
                paddingLeft: "0",
                allowChildren: false,
              },
              content: [
                {
                  id: "05ecc6fd-5912-408b-a5fb-79349f2764fb",
                  type: "Image",
                  attrs: {
                    src:
                      "https://github.com/elm-street-technology/elevate-ui/raw/develop/elevate-ui-logo.png",
                    upload: "",
                    width: 240,
                    height: "",
                    title: "",
                    alt: "Elevate-UI",
                    url: "https://www.elevate-ui.com",
                  },
                  content: [],
                },
              ],
            },
            {
              id: "8b9d9fad-0ac4-455c-8433-7f0788dc920a",
              type: "Row",
              attrs: {
                width: "100%",
                height: "inherit",
                borderSize: 0,
                borderColor: "#000000",
                backgroundColor: "transparent",
                backgroundImage: "",
                backgroundSize: "",
                upload: "",
                direction: "vertical",
                alignment: "",
                paddingTop: "12",
                paddingRight: "0",
                paddingBottom: "12",
                paddingLeft: "0",
                allowChildren: false,
              },
              content: [
                {
                  id: "ac53f5c7-7b2f-4ae5-9f13-25ce3e20b08f",
                  type: "HorizontalRule",
                  attrs: { color: "#a9aaab", thickness: 1 },
                  content: [],
                },
              ],
            },
            {
              id: "8b9d9fad-0ac4-455c-8433-7f0788dc920e",
              type: "Row",
              attrs: {
                width: "100%",
                height: "inherit",
                borderSize: 0,
                borderColor: "#000000",
                backgroundColor: "transparent",
                backgroundImage: "",
                backgroundSize: "",
                upload: "",
                direction: "vertical",
                alignment: "center",
                paddingTop: "12",
                paddingRight: "0",
                paddingBottom: "12",
                paddingLeft: "0",
                allowChildren: false,
              },
              content: [
                {
                  id: "fc6211a4-8a71-4230-9a67-29214dfb0b67",
                  type: "Text",
                  attrs: {
                    value: {
                      blocks: [
                        {
                          key: "2rols",
                          text: "Hello friend,",
                          type: "unstyled",
                          depth: 0,
                          inlineStyleRanges: [],
                          entityRanges: [],
                          data: {},
                        },
                        {
                          key: "didsa",
                          text:
                            "Elevate-UI is an opinionated toolkit of React components and patterns used for the rapid prototyping and development of web apps and sites for Elm Street Technology.",
                          type: "unstyled",
                          depth: 0,
                          inlineStyleRanges: [],
                          entityRanges: [],
                          data: {},
                        },
                        {
                          key: "85itv",
                          text:
                            "It seeks to establish best practices around user-interface and user-experience design, for both the platform's users, as well as the developers.",
                          type: "unstyled",
                          depth: 0,
                          inlineStyleRanges: [],
                          entityRanges: [],
                          data: {},
                        },
                        {
                          key: "evkam",
                          text: "We hope you enjoy!",
                          type: "unstyled",
                          depth: 0,
                          inlineStyleRanges: [],
                          entityRanges: [],
                          data: {},
                        },
                        {
                          key: "1dqcp",
                          text: "- Elm Street Engineering",
                          type: "unstyled",
                          depth: 0,
                          inlineStyleRanges: [],
                          entityRanges: [],
                          data: {},
                        },
                      ],
                      entityMap: {},
                    },
                  },
                  content: [],
                },
              ],
            },
            {
              id: "8b9d9fad-0ac4-455c-8433-7f0788dc920c",
              type: "Row",
              attrs: {
                width: "100%",
                height: "inherit",
                borderSize: 0,
                borderColor: "#000000",
                backgroundColor: "transparent",
                backgroundImage: "",
                backgroundSize: "",
                upload: "",
                direction: "vertical",
                alignment: "center",
                paddingTop: "12",
                paddingRight: "0",
                paddingBottom: "12",
                paddingLeft: "0",
                allowChildren: false,
              },
              content: [
                {
                  id: "27453d04-9ed0-4eb8-91c4-b877b75c97b4",
                  type: "Button",
                  attrs: {
                    children: "Visit Website",
                    fontSize: 18,
                    backgroundColor: "#f15953",
                    color: "#000000",
                    paddingTop: "0",
                    paddingRight: 4,
                    paddingBottom: "0",
                    paddingLeft: 4,
                    url: "https://www.elevate-ui.com",
                  },
                  content: [],
                },
              ],
            },
          ],
        },
        {
          id: "8b9d9fad-0ac4-455c-8433-7f0788dc920d",
          type: "Row",
          attrs: {
            width: "100%",
            height: "inherit",
            borderSize: 0,
            borderColor: "#000000",
            backgroundColor: "transparent",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "center",
            paddingTop: "12",
            paddingRight: "0",
            paddingBottom: "12",
            paddingLeft: "0",
            allowChildren: false,
          },
          content: [
            {
              id: "19f88651-0891-4009-a9d5-edb7b0c3a935",
              type: "Text",
              attrs: {
                value: {
                  blocks: [
                    {
                      key: "2rols",
                      text: "Unsubscribe",
                      type: "unstyled",
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: { "text-align": "center" },
                    },
                  ],
                  entityMap: {},
                },
              },
              content: [],
            },
          ],
        },
      ],
    },
  ],
};
