export default {
  editorMode: "email",
  content: [
    {
      id: "f8043f3e-9e88-46f8-92c0-00aeceddc2ab",
      type: "Wrapper",
      attrs: {
        width: "675",
        borderSize: 1,
        borderColor: "#a9aaab",
        innerBackgroundColor: "#ffffff",
        paddingTop: 20,
        paddingRight: 20,
        paddingBottom: 20,
        paddingLeft: 20,
        backgroundColor: "#E4E4E4",
        allowChildren: true,
        disableDelete: true,
        footer: "[unsubscribe]",
        calculatedWidth: 1408,
        calculatedHeight: 1107,
      },
      content: [
        {
          id: "1288eae8-cd91-4b37-836e-46119a568332",
          type: "Row",
          attrs: {
            width: "100%",
            height: "",
            borderSize: 0,
            borderColor: "#000000",
            backgroundColor: "transparent",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "center",
            paddingTop: "20",
            paddingRight: "8",
            paddingBottom: "0",
            paddingLeft: "8",
            allowChildren: false,
            calculatedWidth: 673,
            calculatedHeight: 86,
          },
          content: [
            {
              id: "25fa8ce4-61e8-490a-b1a4-1f6cada8b74f",
              type: "Image",
              attrs: {
                src:
                  "https://github.com/elm-street-technology/elevate-ui/raw/develop/elevate-ui-logo.png",
                upload: "",
                width: "250pz",
                height: "",
                title: "",
                alt: "",
                url: "",
                calculatedWidth: 250,
                calculatedHeight: 66,
              },
              content: [],
            },
          ],
        },
        {
          id: "cca1227f-aecc-41db-8d72-e4825113a45a",
          type: "Row",
          attrs: {
            width: "100%",
            height: "",
            borderSize: 0,
            borderColor: "#000000",
            backgroundColor: "transparent",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "center",
            paddingTop: 8,
            paddingRight: 8,
            paddingBottom: 8,
            paddingLeft: 8,
            allowChildren: false,
            calculatedWidth: 673,
            calculatedHeight: 550,
          },
          content: [
            {
              id: "23e3c5e4-5224-4485-a1a9-c879cb1d7bbb",
              type: "Row",
              attrs: {
                width: "50%",
                height: "",
                borderSize: 0,
                borderColor: "#000000",
                backgroundColor: "transparent",
                backgroundImage: "",
                backgroundSize: "",
                upload: "",
                direction: "horizontal",
                alignment: "",
                paddingTop: "0",
                paddingRight: "0",
                paddingBottom: "0",
                paddingLeft: "0",
                allowChildren: false,
                calculatedWidth: 328,
                calculatedHeight: 164,
              },
              content: [
                {
                  id: "858ab82e-6654-442b-b08c-94e9ff6e9b7d",
                  type: "Row",
                  attrs: {
                    width: "50%",
                    height: "",
                    borderSize: 0,
                    borderColor: "#000000",
                    backgroundColor: "transparent",
                    backgroundImage: "",
                    backgroundSize: "",
                    upload: "",
                    direction: "vertical",
                    alignment: "",
                    paddingTop: 8,
                    paddingRight: 8,
                    paddingBottom: 8,
                    paddingLeft: 8,
                    allowChildren: false,
                    calculatedWidth: 164,
                    calculatedHeight: 164,
                  },
                  content: [
                    {
                      id: "f79aa46c-68e9-4657-a6ed-8bf2e48793f9",
                      type: "Image",
                      attrs: {
                        src: "https://picsum.photos/125/125/?random",
                        upload: "",
                        width: "100%",
                        height: "",
                        title: "",
                        alt: "",
                        url: "",
                        calculatedWidth: 148,
                        calculatedHeight: 148,
                      },
                      content: [],
                    },
                  ],
                },
                {
                  id: "76777b5c-8977-41ea-8639-35d51e8cf44a",
                  type: "Row",
                  attrs: {
                    width: "50%",
                    height: "",
                    borderSize: 0,
                    borderColor: "#000000",
                    backgroundColor: "transparent",
                    backgroundImage: "",
                    backgroundSize: "",
                    upload: "",
                    direction: "vertical",
                    alignment: "",
                    paddingTop: 8,
                    paddingRight: 8,
                    paddingBottom: 8,
                    paddingLeft: 8,
                    allowChildren: false,
                    calculatedWidth: 164,
                    calculatedHeight: 164,
                  },
                  content: [
                    {
                      id: "6eb9935c-9dde-4d3f-946f-f493ff65ebe8",
                      type: "Image",
                      attrs: {
                        src: "https://picsum.photos/125/125/?random",
                        upload: "",
                        width: "100%",
                        height: "",
                        title: "",
                        alt: "",
                        url: "",
                        calculatedWidth: 148,
                        calculatedHeight: 148,
                      },
                      content: [],
                    },
                  ],
                },
              ],
            },
            {
              id: "58497633-5a92-42a5-b197-02b6f6d6f5ee",
              type: "Row",
              attrs: {
                width: "100%",
                height: "",
                borderSize: 0,
                borderColor: "#000000",
                backgroundColor: "transparent",
                backgroundImage: "",
                backgroundSize: "",
                upload: "",
                direction: "horizontal",
                alignment: "",
                paddingTop: 8,
                paddingRight: 8,
                paddingBottom: 8,
                paddingLeft: 8,
                allowChildren: false,
                calculatedWidth: 657,
                calculatedHeight: 229,
              },
              content: [
                {
                  id: "2963abe6-51ed-4cb7-a8ec-c51b284df04b",
                  type: "Row",
                  attrs: {
                    width: "33.333333333333336%",
                    height: "",
                    borderSize: 0,
                    borderColor: "#000000",
                    backgroundColor: "transparent",
                    backgroundImage: "",
                    backgroundSize: "",
                    upload: "",
                    direction: "vertical",
                    alignment: "",
                    paddingTop: 8,
                    paddingRight: 8,
                    paddingBottom: 8,
                    paddingLeft: 8,
                    allowChildren: false,
                    calculatedWidth: 213,
                    calculatedHeight: 213,
                  },
                  content: [
                    {
                      id: "47f5ffde-ad00-4027-afcc-bd4679f40bb0",
                      type: "Image",
                      attrs: {
                        src: "https://picsum.photos/125/125/?random",
                        upload: "",
                        width: "100%",
                        height: "",
                        title: "",
                        alt: "",
                        url: "",
                        calculatedWidth: 197,
                        calculatedHeight: 197,
                      },
                      content: [],
                    },
                  ],
                },
                {
                  id: "24b654da-8a12-4dc5-ac75-1e4d9e6d5b6c",
                  type: "Row",
                  attrs: {
                    width: "33.333333333333336%",
                    height: "",
                    borderSize: 0,
                    borderColor: "#000000",
                    backgroundColor: "transparent",
                    backgroundImage: "",
                    backgroundSize: "",
                    upload: "",
                    direction: "vertical",
                    alignment: "",
                    paddingTop: 8,
                    paddingRight: 8,
                    paddingBottom: 8,
                    paddingLeft: 8,
                    allowChildren: false,
                    calculatedWidth: 213,
                    calculatedHeight: 213,
                  },
                  content: [
                    {
                      id: "3311154a-c8d4-40f2-b33e-5c4529d413ba",
                      type: "Image",
                      attrs: {
                        src: "https://picsum.photos/125/125/?random",
                        upload: "",
                        width: "100%",
                        height: "",
                        title: "",
                        alt: "",
                        url: "",
                        calculatedWidth: 197,
                        calculatedHeight: 197,
                      },
                      content: [],
                    },
                  ],
                },
                {
                  id: "0b72505d-bc88-41f4-96cb-d3d64112bb8f",
                  type: "Row",
                  attrs: {
                    width: "33.333333333333336%",
                    height: "",
                    borderSize: 0,
                    borderColor: "#000000",
                    backgroundColor: "transparent",
                    backgroundImage: "",
                    backgroundSize: "",
                    upload: "",
                    direction: "vertical",
                    alignment: "",
                    paddingTop: 8,
                    paddingRight: 8,
                    paddingBottom: 8,
                    paddingLeft: 8,
                    allowChildren: false,
                    calculatedWidth: 213,
                    calculatedHeight: 213,
                  },
                  content: [
                    {
                      id: "4a4001b5-b0ce-42dc-b966-82575a125690",
                      type: "Image",
                      attrs: {
                        src: "https://picsum.photos/125/125/?random",
                        upload: "",
                        width: "100%",
                        height: "",
                        title: "",
                        alt: "",
                        url: "",
                        calculatedWidth: 197,
                        calculatedHeight: 197,
                      },
                      content: [],
                    },
                  ],
                },
              ],
            },
            {
              id: "2f11308a-2987-4a70-8dc2-3eaad8efc0ec",
              type: "Row",
              attrs: {
                width: "100%",
                height: "",
                borderSize: 0,
                borderColor: "#000000",
                backgroundColor: "transparent",
                backgroundImage: "",
                backgroundSize: "",
                upload: "",
                direction: "vertical",
                alignment: "center",
                paddingTop: 8,
                paddingRight: 8,
                paddingBottom: 8,
                paddingLeft: 8,
                allowChildren: false,
                calculatedWidth: 657,
                calculatedHeight: 141,
              },
              content: [
                {
                  id: "c1139ff9-735a-4298-a081-61bf92a78cd8",
                  type: "Image",
                  attrs: {
                    src: "https://picsum.photos/125/125/?random",
                    upload: "",
                    width: "",
                    height: "",
                    title: "",
                    alt: "",
                    url: "",
                    calculatedWidth: 125,
                    calculatedHeight: 125,
                  },
                  content: [],
                },
              ],
            },
          ],
        },
        {
          id: "a6ec4a9d-bfae-45b8-81ef-416021506e25",
          type: "Row",
          attrs: {
            width: "100%",
            height: "",
            borderSize: 0,
            borderColor: "#000000",
            backgroundColor: "transparent",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "right",
            paddingTop: 8,
            paddingRight: 8,
            paddingBottom: 8,
            paddingLeft: 8,
            allowChildren: false,
            calculatedWidth: 673,
            calculatedHeight: 316,
          },
          content: [
            {
              id: "86eeb80d-4d7d-417f-a2b5-7765c1083563",
              type: "Image",
              attrs: {
                src: "https://picsum.photos/125/125/?random",
                upload: "",
                width: "300px",
                height: "",
                title: "",
                alt: "",
                url: "",
                calculatedWidth: 300,
                calculatedHeight: 300,
              },
              content: [],
            },
          ],
        },
        {
          id: "1ac69e89-0989-4460-95a5-59b65da98133",
          type: "Row",
          attrs: {
            width: "100%",
            height: "",
            borderSize: 0,
            borderColor: "#000000",
            backgroundColor: "transparent",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "",
            paddingTop: 8,
            paddingRight: 8,
            paddingBottom: 8,
            paddingLeft: 8,
            allowChildren: false,
            calculatedWidth: 673,
            calculatedHeight: 49,
          },
          content: [
            {
              id: "8198728b-e212-49b0-91d4-52b72ea03a5b",
              type: "Text",
              attrs: {
                value: {
                  blocks: [
                    {
                      key: "2rols",
                      text: "Your text",
                      type: "unstyled",
                      depth: 0,
                      inlineStyleRanges: [],
                      entityRanges: [],
                      data: {},
                    },
                  ],
                  entityMap: {},
                },
                color: "",
              },
              content: [],
            },
          ],
        },
        {
          id: "86c25c2c-a1c9-4d87-8a74-7b86a8a1e6da",
          type: "Row",
          attrs: {
            width: "100%",
            height: "",
            borderSize: 0,
            borderColor: "#000000",
            backgroundColor: "transparent",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "",
            paddingTop: 4,
            paddingRight: 4,
            paddingBottom: 4,
            paddingLeft: 4,
            allowChildren: false,
            calculatedWidth: 673,
            calculatedHeight: 9,
          },
          content: [
            {
              id: "0248780b-44cb-4b47-bb7f-45d45a1de10d",
              type: "HorizontalRule",
              attrs: { color: "#000000", thickness: 1 },
              content: [],
            },
          ],
        },
        {
          id: "be5033ff-19a1-4d76-b485-3ddb61b10ca9",
          type: "Row",
          attrs: {
            width: "100%",
            height: "",
            borderSize: 0,
            borderColor: "#000000",
            backgroundColor: "transparent",
            backgroundImage: "",
            backgroundSize: "",
            upload: "",
            direction: "vertical",
            alignment: "right",
            paddingTop: 8,
            paddingRight: 8,
            paddingBottom: 8,
            paddingLeft: 8,
            allowChildren: false,
            calculatedWidth: 673,
            calculatedHeight: 54,
          },
          content: [
            {
              id: "b26d06a8-3cb2-422d-a438-7c54646d413e",
              type: "Button",
              attrs: {
                children: "Button Text",
                fontSize: "14",
                backgroundColor: "#5158f4",
                color: "#ffffff",
                paddingTop: "10",
                paddingRight: "30",
                paddingBottom: "10",
                paddingLeft: "30",
                url: "",
              },
              content: [],
            },
          ],
        },
      ],
    },
  ],
};
