export const elevateUI = [
  {
    id: "f8043f3e-9e88-46f8-92c0-00aeceddc2ab",
    type: "Row",
    attrs: {
      width: "100%",
      height: "auto",
      borderSize: 0,
      borderColor: "#000000",
      backgroundColor: "#e4e4e4",
      backgroundImage: "",
      backgroundSize: "",
      upload: "",
      direction: "vertical",
      alignment: "center",
      paddingTop: "4",
      paddingRight: 4,
      paddingBottom: "4",
      paddingLeft: 4,
      allowChildren: true,
      disableDelete: true,
    },
    content: [
      {
        id: "cbf27be5-9975-492f-9e9d-07b7e9d9d757",
        type: "Row",
        attrs: {
          width: "600px",
          height: "inherit",
          borderSize: "1",
          borderColor: "#a9aaab",
          backgroundColor: "#ffffff",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "vertical",
          alignment: "center",
          paddingTop: "8",
          paddingRight: "8",
          paddingBottom: "8",
          paddingLeft: "8",
          allowChildren: true,
        },
        content: [
          {
            id: "69d8db98-3311-49a3-bc9f-78600fdc253e",
            type: "Row",
            attrs: {
              width: "100%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "241b3f7e-7289-4967-a823-124af54abaa2",
                type: "HorizontalRule",
                attrs: { color: "#000000", thickness: 20 },
                content: [],
              },
            ],
          },
          {
            id: "e451aed7-88e0-4ac0-b3ec-d48e0d7e59b7",
            type: "Row",
            attrs: {
              width: "100%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "horizontal",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "7a8fd2e6-4954-488f-8f7c-46551c6a3cda",
                type: "Row",
                attrs: {
                  width: "50%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "f8639626-0d1c-414a-819e-ed6fda218f0b",
                    type: "HorizontalRule",
                    attrs: { color: "#1e3afb", thickness: 20 },
                    content: [],
                  },
                ],
              },
              {
                id: "831fc21e-3cc1-4837-b476-78231291d8b5",
                type: "Row",
                attrs: {
                  width: "50%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "fad4c899-b355-4cd5-8ade-bf45a2d6ae3e",
                    type: "HorizontalRule",
                    attrs: { color: "#f637ff", thickness: 20 },
                    content: [],
                  },
                ],
              },
            ],
          },
          {
            id: "960edda0-b9c1-47fa-813f-a7f5d496abcc",
            type: "Row",
            attrs: {
              width: "100%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "horizontal",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "44315ed1-814e-4c20-b25c-e5c03a94690b",
                type: "Row",
                attrs: {
                  width: "33.333333333333336%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "64f202f9-5262-412b-a4a0-ef3fb3ca47dc",
                    type: "HorizontalRule",
                    attrs: { color: "#17ffff", thickness: 20 },
                    content: [],
                  },
                ],
              },
              {
                id: "76a7daab-19eb-4490-8131-c7c9b51b620f",
                type: "Row",
                attrs: {
                  width: "33.333333333333336%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "19be1f0c-9f1c-4d2e-865d-98c9184a1885",
                    type: "HorizontalRule",
                    attrs: { color: "#ff2b09", thickness: 20 },
                    content: [],
                  },
                ],
              },
              {
                id: "56c70c6c-93f0-490d-9bd7-0bbc5b6fe1f8",
                type: "Row",
                attrs: {
                  width: "33.333333333333336%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "c087199f-c351-49d0-88cd-867eb32a0f1c",
                    type: "HorizontalRule",
                    attrs: { color: "#1fff15", thickness: 20 },
                    content: [],
                  },
                ],
              },
            ],
          },
          {
            id: "bd5945c1-1d05-4552-b4cc-76572adc16df",
            type: "Row",
            attrs: {
              width: "100%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "horizontal",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "c57ac44a-39cb-47aa-9ab1-6290a6b3b710",
                type: "Row",
                attrs: {
                  width: "25%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "6982971d-3868-4848-b685-6d5c613ebf93",
                    type: "HorizontalRule",
                    attrs: { color: "#f9f600", thickness: 20 },
                    content: [],
                  },
                ],
              },
              {
                id: "9805e4bc-a1d6-4bfe-bfa7-f5507b7690cd",
                type: "Row",
                attrs: {
                  width: "25%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "c30f1b7d-707b-44bc-92cd-12baf22a8f9d",
                    type: "HorizontalRule",
                    attrs: { color: "#ff7c00", thickness: 20 },
                    content: [],
                  },
                ],
              },
              {
                id: "8ed943e0-58f0-4e9a-b2ec-5fc28f1dc2f4",
                type: "Row",
                attrs: {
                  width: "25%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "aa0f2de6-b7e1-4e1f-991f-e7dc84ac8716",
                    type: "HorizontalRule",
                    attrs: { color: "#ae08ff", thickness: 20 },
                    content: [],
                  },
                ],
              },
              {
                id: "3a79bf88-4d49-4b44-b626-ea995e83c8e6",
                type: "Row",
                attrs: {
                  width: "25%",
                  height: "inherit",
                  borderSize: 0,
                  borderColor: "#000000",
                  backgroundColor: "transparent",
                  backgroundImage: "",
                  backgroundSize: "",
                  upload: "",
                  direction: "vertical",
                  alignment: "",
                  paddingTop: 8,
                  paddingRight: 8,
                  paddingBottom: 8,
                  paddingLeft: 8,
                  allowChildren: false,
                },
                content: [
                  {
                    id: "5aa5d78b-16c9-4bd5-aa52-97b6caae6ee9",
                    type: "HorizontalRule",
                    attrs: { color: "#0085ff", thickness: 20 },
                    content: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "8b9d9fad-0ac4-455c-8433-7f0788dc920d",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "vertical",
          alignment: "center",
          paddingTop: "12",
          paddingRight: "0",
          paddingBottom: "12",
          paddingLeft: "0",
          allowChildren: false,
        },
        content: [
          {
            id: "19f88651-0891-4009-a9d5-edb7b0c3a935",
            type: "Text",
            attrs: {
              value: {
                blocks: [
                  {
                    key: "2rols",
                    text: "Unsubscribe",
                    type: "unstyled",
                    depth: 0,
                    inlineStyleRanges: [],
                    entityRanges: [],
                    data: {},
                  },
                ],
                entityMap: {},
              },
            },
            content: [],
          },
        ],
      },
    ],
  },
];
