export default [
  {
    id: "f8043f3e-9e88-46f8-92c0-00aeceddc2ab",
    type: "Row",
    attrs: {
      width: "100%",
      height: "auto",
      borderSize: 0,
      borderColor: "#000000",
      backgroundColor: "#ffffff",
      backgroundImage: "",
      backgroundSize: "",
      upload: "",
      direction: "vertical",
      alignment: "center",
      paddingTop: "4",
      paddingRight: 4,
      paddingBottom: "8",
      paddingLeft: 4,
      allowChildren: true,
      disableDelete: true,
    },
    content: [
      {
        id: "d503fe38-c2f8-4442-aebd-f123634a19a2",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "horizontal",
          alignment: "",
          paddingTop: 8,
          paddingRight: 8,
          paddingBottom: "0",
          paddingLeft: 8,
          allowChildren: false,
        },
        content: [
          {
            id: "79135a1b-6107-4db2-ac29-d9c8389113e7",
            type: "Row",
            attrs: {
              width: "50%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "0e61baac-270d-4457-b4f4-36e56d5e0d3e",
                type: "Image",
                attrs: {
                  src: "https://picsum.photos/700/400/?random",
                  upload: "",
                  width: "",
                  height: "",
                  title: "",
                  alt: "",
                  url: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "90e7625b-9255-4716-88b6-880c067de793",
            type: "Row",
            attrs: {
              width: "50%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: "8",
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "0840ba93-a2f3-4531-957c-887c3b3e85a8",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "Your Chance To Experience Paradise... ",
                        type: "header-one",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "u9oc",
                        text: "",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "alct3",
                        text: "",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
        ],
      },
      {
        id: "c1deffec-b1e9-43bc-9045-9e0cc56d810d",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "horizontal",
          alignment: "",
          paddingTop: "0",
          paddingRight: "0",
          paddingBottom: "0",
          paddingLeft: "0",
          allowChildren: false,
        },
        content: [
          {
            id: "d0f517df-dcbf-4313-874d-eead6c9cdc0f",
            type: "Row",
            attrs: {
              width: "25%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "9c04a9f7-f2c1-4a1c-8a0b-632f1cff3744",
                type: "Image",
                attrs: {
                  src: "https://picsum.photos/697/450/?random",
                  upload: "",
                  width: "",
                  height: "",
                  title: "",
                  alt: "",
                  url: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "d65fa52b-602b-40c0-ab68-0d96392fee7f",
            type: "Row",
            attrs: {
              width: "25%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "0a28b6bb-73df-4f75-b950-5878a4eb75a4",
                type: "Image",
                attrs: {
                  src: "https://picsum.photos/698/450/?random",
                  upload: "",
                  width: "",
                  height: "",
                  title: "",
                  alt: "",
                  url: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "09c3a5a6-81a6-42c9-8675-bb0287b0bc77",
            type: "Row",
            attrs: {
              width: "25%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "0e971ff8-729c-44b9-a6d8-f316df1bbef2",
                type: "Image",
                attrs: {
                  src: "https://picsum.photos/699/450/?random",
                  upload: "",
                  width: "",
                  height: "",
                  title: "",
                  alt: "",
                  url: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "d32483f4-a9e6-468e-927d-d5e16d540a38",
            type: "Row",
            attrs: {
              width: "25%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "125364b4-b017-4c13-812e-a8ff57a28ed2",
                type: "Image",
                attrs: {
                  src: "https://picsum.photos/700/450/?random",
                  upload: "",
                  width: "",
                  height: "",
                  title: "",
                  alt: "",
                  url: "",
                },
                content: [],
              },
            ],
          },
        ],
      },
      {
        id: "c1f5afde-d0f4-4b0a-a4de-fc8bfb9be86f",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "vertical",
          alignment: "",
          paddingTop: "0",
          paddingRight: "0",
          paddingBottom: "0",
          paddingLeft: "0",
          allowChildren: false,
        },
        content: [
          {
            id: "ba2307fa-7c25-4d4c-a097-89ffffa4d45e",
            type: "Text",
            attrs: {
              value: {
                blocks: [
                  {
                    key: "2rols",
                    text: "5555 N Fake Road, Blue Valley, AZ 85253",
                    type: "header-three",
                    depth: 0,
                    inlineStyleRanges: [],
                    entityRanges: [],
                    data: { "text-align": "center" },
                  },
                ],
                entityMap: {},
              },
              color: "",
            },
            content: [],
          },
        ],
      },
      {
        id: "b0091af4-49e3-49b0-b247-4b991674783a",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "vertical",
          alignment: "",
          paddingTop: "0",
          paddingRight: "0",
          paddingBottom: "0",
          paddingLeft: "0",
          allowChildren: false,
        },
        content: [
          {
            id: "c1ecb0bd-8f2b-4a5b-aaed-dd8d809c90fe",
            type: "Text",
            attrs: {
              value: {
                blocks: [
                  {
                    key: "2rols",
                    text: "PRICE: $16,950,000 | ML 555444333",
                    type: "unstyled",
                    depth: 0,
                    inlineStyleRanges: [
                      { offset: 0, length: 31, style: "BOLD" },
                    ],
                    entityRanges: [],
                    data: { "text-align": "center" },
                  },
                ],
                entityMap: {},
              },
              color: "",
            },
            content: [],
          },
        ],
      },
      {
        id: "2296d55e-b02a-463f-8cac-0a74925cb5b6",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "horizontal",
          alignment: "",
          paddingTop: "0",
          paddingRight: "0",
          paddingBottom: "0",
          paddingLeft: "0",
          allowChildren: false,
        },
        content: [
          {
            id: "5153fe52-0132-4759-adaa-6049edec1012",
            type: "Row",
            attrs: {
              width: "50%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: "0",
              paddingRight: "0",
              paddingBottom: "0",
              paddingLeft: "0",
              allowChildren: false,
            },
            content: [
              {
                id: "9c8c9d4e-ad7d-43aa-a755-04a52aa130f7",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "LOT SIZE: 85,912",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 9, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "chht3",
                        text: "BEDROOMS: 3",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 9, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "8dd7t",
                        text: "PARKING: 3",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 8, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "dq86h",
                        text: "FLOORS: -",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 7, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "60357d6e-dd29-4d65-888b-852dfb5e42ba",
            type: "Row",
            attrs: {
              width: "50%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: "",
              paddingRight: "0",
              paddingBottom: "0",
              paddingLeft: "0",
              allowChildren: false,
            },
            content: [
              {
                id: "3a538296-5e37-4289-ac1b-e049cfd5f60c",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "YEAR BUILT: 1555",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 11, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "8nhco",
                        text: "SQFT: 2,483",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 5, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "1lv16",
                        text: "BATHS: 5",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 6, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "d9nhl",
                        text: "SUBDIVISION: -",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [
                          { offset: 0, length: 12, style: "BOLD" },
                        ],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
        ],
      },
      {
        id: "5aff284e-8ed9-477c-977b-16cc5d15cbc7",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "vertical",
          alignment: "",
          paddingTop: 8,
          paddingRight: 8,
          paddingBottom: "0",
          paddingLeft: 8,
          allowChildren: false,
        },
        content: [
          {
            id: "b107f751-155e-4f1b-a1fe-429652889707",
            type: "Text",
            attrs: {
              value: {
                blocks: [
                  {
                    key: "2rols",
                    text: "PROPERTY FEATURES:",
                    type: "unstyled",
                    depth: 0,
                    inlineStyleRanges: [
                      { offset: 0, length: 18, style: "color-rgb(46,46,53)" },
                      {
                        offset: 0,
                        length: 18,
                        style: "bgcolor-rgb(255,255,255)",
                      },
                      { offset: 0, length: 18, style: "fontsize-14" },
                      {
                        offset: 0,
                        length: 18,
                        style: 'fontfamily-Open Sans", sans-serif',
                      },
                      { offset: 0, length: 18, style: "fontfamily-inherit" },
                      { offset: 0, length: 18, style: "BOLD" },
                    ],
                    entityRanges: [],
                    data: { "text-align": "start" },
                  },
                ],
                entityMap: {},
              },
              color: "",
            },
            content: [],
          },
        ],
      },
      {
        id: "279e6922-1e68-403f-8e03-9341c3d58a39",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "horizontal",
          alignment: "",
          paddingTop: "0",
          paddingRight: 8,
          paddingBottom: "0",
          paddingLeft: 8,
          allowChildren: false,
        },
        content: [
          {
            id: "3a336f5e-e530-431d-bfb7-598e09e9725d",
            type: "Row",
            attrs: {
              width: "33.333333333333336%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: "0",
              paddingRight: 8,
              paddingBottom: "0",
              paddingLeft: "0",
              allowChildren: false,
            },
            content: [
              {
                id: "b492aa5d-d03f-495d-8fe7-994de2ffbd4c",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "4sstb",
                        text: "Breakfast Nook",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "dd2eb",
                        text: "Granite Countertops",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "92tj5",
                        text: "Refridgerator",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "7jc7d",
                        text: "Central A/C",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "avm88",
                        text: "Hardwood Floors",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "dvhke",
                        text: "Sauna",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "36q7j",
                        text: "Central Heat",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "7vs53",
                        text: "Fireplace",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "623m5",
                        text: "Stainless Appliances",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "e42f9850-2044-410e-b029-cde16537405c",
            type: "Row",
            attrs: {
              width: "33.333333333333336%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: "0",
              paddingRight: "0",
              paddingBottom: "0",
              paddingLeft: "0",
              allowChildren: false,
            },
            content: [
              {
                id: "e5be1e8f-3b14-4942-b44a-0b781431ed3f",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "Dining Room",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "6padj",
                        text: "Jacuzzi / Whirlpool",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "b3mcs",
                        text: "Stove / Oven",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "6lq4r",
                        text: "Dishwasher",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "4c7h9",
                        text: "Laundry Area - Garage",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "a5c8o",
                        text: "Swimming Pool",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "c7i10",
                        text: "Laundry Area - Inside",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "5omva",
                        text: "Tile Floor",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "873a0084-0ec0-47d8-9728-a8c92e911b1e",
            type: "Row",
            attrs: {
              width: "33.333333333333336%",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: "0",
              paddingRight: "0",
              paddingBottom: "0",
              paddingLeft: "0",
              allowChildren: false,
            },
            content: [
              {
                id: "6675d6c4-fe43-4276-b3cc-cc15c0b33f6d",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "Family Room",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "ajrjg",
                        text: "Living Room",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "1rd6u",
                        text: "Walk-in Closet",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "fd93h",
                        text: "Fin. Room Over Garage",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "2ulsf",
                        text: "Microwave",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "8vgeu",
                        text: "Washer",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "bva7a",
                        text: "High / Vaulted Ceiling",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "65k5g",
                        text: "Office / Den",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "ipnu",
                        text: "Yard",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
        ],
      },
      {
        id: "659f79dc-77f9-402c-9492-8d906351d039",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "vertical",
          alignment: "",
          paddingTop: 8,
          paddingRight: 8,
          paddingBottom: "",
          paddingLeft: 8,
          allowChildren: false,
        },
        content: [
          {
            id: "f8672067-014e-4ec3-b6b1-c4a58dd2c67d",
            type: "Text",
            attrs: {
              value: {
                blocks: [
                  {
                    key: "2rols",
                    text: "OTHER FEATURES:",
                    type: "unstyled",
                    depth: 0,
                    inlineStyleRanges: [
                      { offset: 0, length: 15, style: "color-rgb(46,46,53)" },
                      {
                        offset: 0,
                        length: 15,
                        style: "bgcolor-rgb(255,255,255)",
                      },
                      { offset: 0, length: 15, style: "fontsize-14" },
                      {
                        offset: 0,
                        length: 15,
                        style: 'fontfamily-Open Sans", sans-serif',
                      },
                      { offset: 0, length: 15, style: "fontfamily-inherit" },
                      { offset: 0, length: 15, style: "BOLD" },
                    ],
                    entityRanges: [],
                    data: { "text-align": "start" },
                  },
                ],
                entityMap: {},
              },
              color: "",
            },
            content: [],
          },
        ],
      },
      {
        id: "74d92c72-7477-4796-bb40-b54bff1800cf",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "horizontal",
          alignment: "",
          paddingTop: "0",
          paddingRight: 8,
          paddingBottom: "0",
          paddingLeft: 8,
          allowChildren: false,
        },
        content: [
          {
            id: "f66e7f10-a3ff-44af-8afc-0364b2668b7f",
            type: "Row",
            attrs: {
              width: "",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: "0",
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "e49cdf4f-b8fe-4031-9975-23765a161500",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "3gdku",
                        text: "Shed",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
          {
            id: "8e351e8f-e65f-4ec4-8f2a-5709be11af20",
            type: "Row",
            attrs: {
              width: "",
              height: "inherit",
              borderSize: 0,
              borderColor: "#000000",
              backgroundColor: "transparent",
              backgroundImage: "",
              backgroundSize: "",
              upload: "",
              direction: "vertical",
              alignment: "",
              paddingTop: "0",
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              allowChildren: false,
            },
            content: [
              {
                id: "ee82f80d-2a60-4e3d-9a2c-7398fb215982",
                type: "Text",
                attrs: {
                  value: {
                    blocks: [
                      {
                        key: "2rols",
                        text: "",
                        type: "unstyled",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                      {
                        key: "dqu1j",
                        text: "Lake",
                        type: "unordered-list-item",
                        depth: 0,
                        inlineStyleRanges: [],
                        entityRanges: [],
                        data: {},
                      },
                    ],
                    entityMap: {},
                  },
                  color: "",
                },
                content: [],
              },
            ],
          },
        ],
      },
      {
        id: "2acbb651-446c-4cb4-b6e5-ed7a05973c82",
        type: "Row",
        attrs: {
          width: "100%",
          height: "inherit",
          borderSize: 0,
          borderColor: "#000000",
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "",
          upload: "",
          direction: "vertical",
          alignment: "",
          paddingTop: "0",
          paddingRight: "12",
          paddingBottom: "0",
          paddingLeft: "12",
          allowChildren: false,
        },
        content: [
          {
            id: "f0f96cb8-7be3-427b-877c-f0d1a294517d",
            type: "Text",
            attrs: {
              value: {
                blocks: [
                  {
                    key: "2rols",
                    text:
                      "Simple words cannot describe an estate of this stature. The polished elegance and imposing beauty are what movies are made of, and it's easy to imagine many a movie being filmed in this magnificent showpiece. The rooms are so luxurious and so unique, it's impossible to convey the grandeur without seemingly exaggerating, and to say that this mansion is constructed with quality materials is a massive understatement, as it has been built with commercial standards and engineering that are rarely, if ever, seen in residential construction. If that doesn't get your attention, the 25-person elevator sure will, serving as a focal point so spectacular that it will take your breath away. Impeccable custom design adorns every inch of this palatial residence, including a full home theatre.",
                    type: "unstyled",
                    depth: 0,
                    inlineStyleRanges: [],
                    entityRanges: [],
                    data: {},
                  },
                ],
                entityMap: {},
              },
              color: "",
            },
            content: [],
          },
        ],
      },
    ],
  },
];
